%%
%% This is file `UWMadThesis.cls',
%% generated with the docstrip utility.
%%
%% The original source files were:
%%
%% UWMadThesis.dtx  (with options: `class')
%% UWMadThesis.Implementation.dtx 
%% -----------------------------------------------------------------------
%% UWMadThesis --- A thesis class for the University of Wisconsin-Madison
%% E-mail: UWMadThesis@hask.in
%% Released under the LaTeX Project Public License v1.3c or later
%% See http://www.latex-project.org/lppl.txt
%% -----------------------------------------------------------------------
%% 
\NeedsTeXFormat{LaTeX2e}[1999/12/01]
\ProvidesClass{UWMadThesis}
    [2013/06/01 v1.0 A thesis class for the University of Wisconsin-Madison]
\LoadClassWithOptions{article}
\newcommand{\dummyMacro}{}
\newenvironment{dummyEnv}{}{}%
%% 
%% Copyright (C) 2013 by Troy C. Haskin <UWMadThesis@hask.in>
%% 
%% This work may be distributed and/or modified under the
%% conditions of the LaTeX Project Public License (LPPL), either
%% version 1.3c of this license or (at your option) any later
%% version.  The latest version of this license is in the file:
%% 
%% http://www.latex-project.org/lppl.txt
%% 
%% This work is "maintained" (as per LPPL maintenance status) by
%% Troy C. Haskin.
%% 
%% This work consists of the file  UWMadThesis.dtx
%% and the derived files           UWMadThesis.ins,
%%                                 UWMadThesis.pdf, and
%%                                 UWMadThesis.cls.
%% 
%%
%% End of file `UWMadThesis.cls'.
