%%
%% This is file `UWMadThesis.cls',
%% generated with the docstrip utility.
%%
%% The original source files were:
%%
%% ../Development/UWMadThesis2.dtx  (with options: `class')
%%     Copyright (C) 2013 by Troy C. Haskin
%% 
%%     This file may be distributed and/or modified under the
%%     conditions of the LaTeX Project Public License, either
%%     version 1.3c of this license or (at your option) any later
%%     version. The latest version of this license is in:
%% 
%%     http://www.latex-project.org/lppl.txt
%% 
%%     and version 1.3c or later is part of all distributions of
%%     LaTeX version 2005/12/01 or later.
%% 
%%     This work has the LPPL maintenance status `maintained'.
%% 
%%     The Current Maintainer of this work is Troy C. Haskin
\NeedsTeXFormat{LaTeX2e}[1995/12/01]
\ProvidesClass{UWMadThesis}
              [2013/02/18 v0.1 | LaTeX2e Thesis Class for the
               University of Wiconsin-Madison]
\def\HELLO{Hello, World!}
\def\HELLOTwo{Hello, World!}

\endinput
%%
%% End of file `UWMadThesis.cls'.
